version: "3.8"

services:
  jenkin:
    build:
      context: .
    container_name: jenkins
    ports:
        - 80:8080
    volumes:
        - ./jenkins_home:/var/jenkins_home
    restart: unless-stopped
    # use named volume in this example for jenkins_home, if you have any issues with bind mount sample, then this is recommended (named mount) and is way more performant